"""add_actual_minutes_to_todos

Revision ID: 2b286a327970
Revises: 56a8f6bcf0e1
Create Date: 2026-06-07 19:39:50.683175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b286a327970'
down_revision: Union[str, None] = '56a8f6bcf0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('actual_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'actual_minutes')
    # ### end Alembic commands ###
