"""Add goal_embeddings table and pgvector

Revision ID: 56a8f6bcf0e1
Revises: 2fb9b22b6e55
Create Date: 2026-06-07 02:46:25.787757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '56a8f6bcf0e1'
down_revision: Union[str, None] = '2fb9b22b6e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('goal_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_summary', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_embeddings_goal_id'), 'goal_embeddings', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_embeddings_id'), 'goal_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_goal_embeddings_user_id'), 'goal_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_embeddings_user_id'), table_name='goal_embeddings')
    op.drop_index(op.f('ix_goal_embeddings_id'), table_name='goal_embeddings')
    op.drop_index(op.f('ix_goal_embeddings_goal_id'), table_name='goal_embeddings')
    op.drop_table('goal_embeddings')
    # ### end Alembic commands ###
